# -*- coding: utf-8 -*-
"""Weather forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IepBQOHoNoV822bT_l8M6jaOyMlnMsSJ
"""

pip install requests

import requests

def Gen_report(city_name):
    try:
        # Your logic here (e.g., generating a report)
        T = f"Report for {city_name}"
    except Exception as e:
        T = "Error Occurred"
    print(T)

# Define and assign a value to city_name
city_name = "New York"
Gen_report(city_name)

import requests

print("\t\tWelcome to the Weather Forecaster!\n\n")
print("Just Enter the City you want the weather report for and click on the button! It's that simple!\n\n")

city_name = input("Enter the name of the City : ")
print("\n\n")

# Function to Generate Report
def Gen_report(C):
    url = 'https://wttr.in/{}'.format(C)
    try:
        data = requests.get(url)
        T = data.text
    except:
        T = "Error Occurred"
    print(T)

Gen_report(city_name)